version: "3.9"

services:
  ajreport:
    build:
      context: .
      dockerfile: Dockerfile
    image: datavisualization/aj-report:2.1
    restart: always
    ports:
      - "9095:9095"
    links:
      - mysql
    depends_on:
      - mysql
    volumes:
      - ./data/conf:/opt/aj-report/conf
    networks:
      - aj_network

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ajpassword
      # MYSQL_DATABASE: aj_report
    ports:
      - "3306:3306"
    networks:
      - aj_network
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

networks:
  aj_network:
    driver: bridge